const { contextBridge, ipcRenderer } = require('electron');

function subscribe(channel, callback, mapData = (data) => data) {
  const handler = (_event, data) => callback(mapData(data));
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld('electronAPI', {
  sendChatMessage: (text) => ipcRenderer.invoke('chat:send', text),
  stopChatMessage: () => ipcRenderer.invoke('chat:stop'),
  sendAvatarCommand: (command) => ipcRenderer.invoke('avatar:command', command),
  notifyAvatarPlayback: (payload) => ipcRenderer.send('avatar:playback', payload),
  setWindowAlwaysOnTop: (target, enabled) => ipcRenderer.invoke('window:set-always-on-top', target, enabled),
  getAppState: () => ipcRenderer.invoke('app:get-state'),
  setSelectedBrain: (brainId) => ipcRenderer.invoke('brain:set-selected', brainId),
  setOllamaConfig: (config) => ipcRenderer.invoke('brain:set-ollama-config', config),
  testBrain: (brainId) => ipcRenderer.invoke('brain:test', brainId),
  openWorkspaceFolder: () => ipcRenderer.invoke('workspace:open-folder'),
  completeWorkspaceBootstrap: () => ipcRenderer.invoke('workspace:complete-bootstrap'),
  getChatHistory: () => ipcRenderer.invoke('chat:get-history'),
  getCanvasState: () => ipcRenderer.invoke('canvas:get-state'),
  openCanvas: (payload) => ipcRenderer.invoke('canvas:open', payload),
  updateCanvas: (payload) => ipcRenderer.invoke('canvas:update', payload),
  closeCanvas: () => ipcRenderer.invoke('canvas:close'),
  setCanvasLayout: (layout) => ipcRenderer.invoke('canvas:set-layout', layout),
  browserNavigate: (payload) => ipcRenderer.invoke('browser:navigate', payload),
  browserRefresh: (payload) => ipcRenderer.invoke('browser:refresh', payload),
  browserAction: (payload) => ipcRenderer.invoke('browser:action', payload),
  readClipboardText: () => ipcRenderer.invoke('clipboard:read-text'),
  writeClipboardText: (text) => ipcRenderer.invoke('clipboard:write-text', text),
  onAvatarCommand: (callback) => subscribe('avatar-command', callback),
  onAvatarStatus: (callback) => subscribe('avatar-status', callback),
  onChatStream: (callback) => subscribe('chat-stream', callback),
  onCanvasState: (callback) => subscribe('canvas-state', callback),
  shellRun: (command, options) => ipcRenderer.invoke('shell:run', command, options),
  shellStop: (processId) => ipcRenderer.invoke('shell:stop', processId),
  shellList: () => ipcRenderer.invoke('shell:list'),
  fileRead: (filePath, options) => ipcRenderer.invoke('file:read', filePath, options),
  fileWrite: (filePath, content, options) => ipcRenderer.invoke('file:write', filePath, content, options),
  fileEdit: (filePath, options) => ipcRenderer.invoke('file:edit', filePath, options),
  fileDelete: (filePath) => ipcRenderer.invoke('file:delete', filePath),
  fileList: (dirPath) => ipcRenderer.invoke('file:list', dirPath),
  searchGlob: (pattern, searchPath) => ipcRenderer.invoke('search:glob', pattern, searchPath),
  searchGrep: (pattern, searchPath, options) => ipcRenderer.invoke('search:grep', pattern, searchPath, options),
  searchMultiRead: (filePaths, options) => ipcRenderer.invoke('search:multi-read', filePaths, options),
  gitRun: (action, params, cwd) => ipcRenderer.invoke('git:run', action, params, cwd),
  webFetch: (url, options) => ipcRenderer.invoke('web:fetch', url, options),
  webSearch: (query, options) => ipcRenderer.invoke('web:search', query, options),
  taskRun: (action, params) => ipcRenderer.invoke('task:run', action, params),
  taskSummary: () => ipcRenderer.invoke('task:summary'),
  frustrationDetect: (text) => ipcRenderer.invoke('frustration:detect', text),
  circuitBreakerStatus: () => ipcRenderer.invoke('circuit-breaker:status'),
  circuitBreakerReset: () => ipcRenderer.invoke('circuit-breaker:reset'),
  dreamStatus: () => ipcRenderer.invoke('dream:status'),
  personalityGet: () => ipcRenderer.invoke('personality:get'),
  personalityPrompt: () => ipcRenderer.invoke('personality:prompt'),
  promptStats: () => ipcRenderer.invoke('prompt:stats'),
});
